# Generated by Django 3.0.7 on 2020-06-06 21:27

import API.models.picture
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20200606_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_url', models.ImageField(upload_to=API.models.picture.upload_to)),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Picture'),
        ),
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Picture'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='API.Picture'),
        ),
    ]
