# Generated by Django 3.0.7 on 2020-06-06 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20200606_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='url_to_upload',
            field=models.CharField(default='', max_length=200),
        ),
    ]
